[package]
name = "abacus"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
miette = { version = "7.6.0", features = ["fancy", "derive"] }
rustyline = "17.0.2"
thiserror = "2.0.17"
unicode-width = "0.1"
